### ISSUE TITLE
Deprecate the use of `hubmap_commons.type_client`

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/user-templates-api#58]
https://github.com/hubmapconsortium/user-templates-api/blob/916ac947d4b37d62ef70b6f753ffd4e49b868641/src/user_templates_api/utils/client.py#L8

Should also configure `TYPE_SERVICE_ENDPOINT` by pointing to UBKG ontology-api endpoint.

**Comment by jpuerto-psc** [comment]
Closing as this has been done by Harvard team.
